vpc_id = "vpc-aae401d3"
database_name = "potgres"
db_instance_identifier = "database-1"
jdbc_target_path = "postgres/%"
secrets_manager_secret_name = "rds_glue"
glue_catalog_db_name = "banks"
glue_crawler_name = ""
s3_etl_bucket_name = ""
